# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'active.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


# This is a test Widget which can be used for a tab
class ActiveTab(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        layout = QtWidgets.QVBoxLayout(self)
        
        self.tableWidget = QtWidgets.QTableWidget()
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 751, 461))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        
        _translate = QtCore.QCoreApplication.translate
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Company"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Position"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Status"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Date"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Feedback"))
        
        layout.addWidget(self.tableWidget)
    
    def add_application(self, company, position, status, date, feedback):
        #Create a empty row at bottom of table
        numRows = self.tableWidget.rowCount()
        self.tableWidget.insertRow(numRows)     
        #Add text to the row
        self.tableWidget.setItem(numRows, 0, QtWidgets.QTableWidgetItem(numRows))
        self.tableWidget.setItem(numRows, 1, QtWidgets.QTableWidgetItem(company))
        self.tableWidget.setItem(numRows, 2, QtWidgets.QTableWidgetItem(position))
        self.tableWidget.setItem(numRows, 3, QtWidgets.QTableWidgetItem(status))
        self.tableWidget.setItem(numRows, 4, QtWidgets.QTableWidgetItem(date))
        self.tableWidget.setItem(numRows, 5, QtWidgets.QTableWidgetItem(feedback))
        
        return
