# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'New_Active.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkFrame = QtWidgets.QFrame(Form)
        self.checkFrame.setMinimumSize(QtCore.QSize(0, 50))
        self.checkFrame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.checkFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.checkFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.checkFrame.setObjectName("checkFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.checkFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.aktivBox = QtWidgets.QCheckBox(self.checkFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.aktivBox.setFont(font)
        self.aktivBox.setChecked(True)
        self.aktivBox.setTristate(False)
        self.aktivBox.setObjectName("aktivBox")
        self.verticalLayout_2.addWidget(self.aktivBox, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.checkFrame, 0, QtCore.Qt.AlignTop)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.aktivBox.setText(_translate("Form", "Aktiv"))
